import type { Metadata } from 'next'
import { IBM_Plex_Mono, Source_Sans_3 } from 'next/font/google'
import '../styles/globals.scss'
import { UserProvider } from '@/context/UserContext'

export const ibmPlexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--ibmPlexMono',
})

export const sourceSans3 = Source_Sans_3({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--sourceSans3',
})

export const metadata: Metadata = {
  title: 'Workout Your Way',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${ibmPlexMono.variable} ${sourceSans3.variable}`}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  )
}
